version: "3"
services:
  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.22
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    ports:
      - "4317:4317"        # OTLP gRPC receiver
    depends_on:
      - jaeger-all-in-one
    volumes:
      - $PWD/otel:/etc/otel:ro
    command: ["--config", "/etc/otel/config.yml"]
