receivers:
  otlp:
    protocols:
      grpc:
  hostmetrics:
    collection_interval: 1m
    scrapers:
      cpu:
      load:
      memory:
      disk:
      filesystem:
      network:
      paging:
      processes:

processors:
  batch:

exporters:
  logging:
    loglevel: debug
  jaeger:
    # this address is resolved in the container
    # so service names work
    endpoint: jaeger:14250
    insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, jaeger]
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [batch]
      exporters: [logging]
